### ISSUE TITLE
PyPi Upload

### ISSUE THREAD

**Issue by S4NT14G0** [ovh/celery-dyrygent#21]
Hello I need to use this library for a project.  I've created a pypi release.  https://pypi.org/project/celery-dyrygent/

It would be appropriate to transfer the ownership to you.  Do you have a pypi User that I can change ownership over to?

**Comment by brabiega** [comment]
Hello, thank you very much for the pypi release. It should've been done a long time ago but for some reason I always get distracted by other things :)

It would be great if you could transfer the ownership to account ovh / pypi@corp.ovh.com

Thanks!

**Comment by S4NT14G0** [comment]
Great I've gone ahead and sent the request to invite ovh as an owner.  I did have to make a minor update to the setup.py classifiers in order to make it compatible with pypi, but it should be fairly comparable to what was there originally.  


Also wanted to give kudos on the library.  We are running complex workflows in celery and were constrained once we started adding too many tasks.  With dyrygent we are now able to run a complex workflow with over 50 tasks.  I've gone ahead and forked the library as we may customize it for internal use, but if there are any improvements that can be beneficial to other users I will open issues and we can find a way to get it integrated back into the main repo.  Cheers!

![image](https://user-images.githubusercontent.com/10766443/150820643-e4936f4c-67d2-43c6-be93-16e6f981ca85.png)

**Comment by brabiega** [comment]
@S4NT14G0  we've accepted the transfer and removed you from collaborators.

If there's any need for you to be a collaborator on pypi, please don't hesitate to contact.

Just FYI, we're running the lib on prod since the early days and we've processed workflows with ~10k tasks without issues.

Good luck.
