### ISSUE TITLE
Extend the capabilities of WorkflowNode

### ISSUE THREAD

**Issue by abak** [ovh/celery-dyrygent#3]
One of the things i wanted to do in my first experimentations was to add data to the nodes, so that i can serialize it.

I can offer a technical solution if you believe it's of interest.

**Comment by brabiega** [comment]
Hello, could you please describe your use case a little bit?
Technically I don't see any obstacles for such implementation but I'd like to understand such need.

**Comment by abak** [comment]
Sure. 
I use celery-dyrygent in a larger ecosystem, that makes use of DAGs, and has its own json format for storing them. I am building a web app that receives those DAGs and converts them into `Workflow`, in order to use celery as an execution backend.
I basically need to keep a conversion between the celery task id and the "outside" task id.

As far as i understand, i have other options, like:

- passing the outside task id as a kwarg
- persisting the conversion in redis or something

but both these solutions seem less clean to me.

**Comment by brabiega** [comment]
Sounds like an interesting use case. And I think you're right this seems to be the cleanest solution.

1 more question, the additional data which you would pass to ```WorkflowNode``` won't be available for the Celery task it wraps. Such data will only be available for workflow processor and workflow instance during signal handling. Are you ok with that?

**Comment by abak** [comment]
Yeah, that is correct. My first idea was to parametrize the type of the underlying task, in order to replace the celery task by something deriving from it, that could contain my additional data, but i didn't find any clean way to do that, but perhaps i just couldn't find a correct way to do it.

**Comment by abak** [comment]
As for the access for the underlying celery task, i did not think of that. I do not think it is that big a deal, since i mostly see `user_params` as a way to add metadata to a task, not actual data that is relevant to the task running.
